core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path, reverse

urlpatterns = [
    path('', lambda x: HttpResponseRedirect(reverse('dashboard:index'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('answers/', include('answers.urls')),
    path('clients/', include('clients.urls')),
    path('assessments/client-<int:client_pk>/', include('assessments.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('questionnaires/', include('questionnaires.urls')),
    path('sections/qre-<int:qre_pk>/', include('sections.urls')),
    path('questions/qre-<int:qre_pk>/section-<int:section_pk>/',
         include('questions.urls'))
]

questionnaires/urls.py
from django.urls import path

from . import views

app_name = 'qres'
urlpatterns = [
    path('create/', views.QreCreateView.as_view(), name='create'),
    path('list/', views.QreListView.as_view(), name='list'),
    path('detail-questionnaire-<int:pk>/', views.QreDetailView.as_view(), name='detail'),
    path('rename-questionnaire-<int:pk>/', views.QreRenameView.as_view(), name='rename'),
    path('delete-questionnaire-<int:pk>/', views.QreDeleteView.as_view(), name='delete'),
]

questions/urls.py
from django.urls import path

from . import views

app_name = 'questions'

urlpatterns = [

    # Questions...
    path('create-question/',
         views.QuestionCreateView.as_view(),
         name='create'),
    path('question-list/',
         views.QuestionListView.as_view(),
         name='list'),
    path('move-question-<int:pk>-<direction>/',
         views.QuestionMoveView.as_view(),
         name='move'),
    path('question-detail-<int:pk>/',
         views.QuestionDetailView.as_view(),
         name='detail'),
    path('update-question-<int:pk>/',
         views.QuestionUpdateView.as_view(),
         name='update'),
    path('delete-question-<int:pk>/',
         views.QuestionDeleteView.as_view(),
         name='delete'),
]

sections/urls.py
from django.urls import path, include

from . import views

app_name = 'sections'

urlpatterns = [

    path('create-section/',
         views.SectionCreateView.as_view(),
         name='create'),
    path('section-list/',
         views.SectionListView.as_view(),
         name='list'),
    path('move-section-<int:pk>-<direction>/',
         views.SectionMoveView.as_view(),
         name='move'),
    path('detail-section-<int:pk>/',
         views.SectionDetailView.as_view(),
         name='detail'),
    path('update-section-<int:pk>/',
         views.SectionUpdateView.as_view(),
         name='update'),
    path('delete-section-<int:pk>/',
         views.SectionDeleteView.as_view(),
         name='delete'),
]

questions/models.py
from django.db import models

from ordered_model.models import OrderedModel


class Question(OrderedModel):
    """A model representing a question that belongs to an assessment section."""

    section = models.ForeignKey('sections.Section', related_name='questions', on_delete=models.CASCADE)
    question = models.TextField()
    weight = models.DecimalField(max_digits=2, decimal_places=1, default=1)
    choice_text_1 = models.TextField(blank=True)
    choice_text_2 = models.TextField(blank=True)
    choice_text_3 = models.TextField(blank=True)
    choice_text_4 = models.TextField(blank=True)
    choice_text_5 = models.TextField(blank=True)
    max_score = models.DecimalField(max_digits=5, decimal_places=1, default=5)
    order_with_respect_to = ('section',)

    class Meta(OrderedModel.Meta):
        """Meta required to inherit from ``OrderedModel.Meta`` (https://github.com/bfirsh/django-ordered-model)."""

        pass

    def __str__(self):
        return f'{self.section.order + 1}.{self.order  + 1}. {self.question}'

    def save(self, *args, **kwargs):
        """Recalculate max score."""
        self.max_score = self.weight * 5
        super().save(*args, **kwargs)

questions/forms.py
from django import forms

from crispy_forms.bootstrap import StrictButton
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Div, Field, Layout

from .models import Question


class QuestionForm(forms.ModelForm):

    class Meta:
        fields = (
            'section',
            'question',
            'weight',
            'choice_text_1',
            'choice_text_2',
            'choice_text_3',
            'choice_text_4',
            'choice_text_5',
        )
        model = Question

    def __init__(self, *args, **kwargs):
        """Initialise crispy forms."""
        super().__init__(*args, **kwargs)

        self.helper = FormHelper()
        self.helper.form_id = 'question_update_form' if self.instance.pk else 'question_create_form'

        choice_fields = [Div(Field(f'choice_text_{i}', style='height:100px'), css_class='col-md') for i in range(1, 6)]
        self.helper.layout = Layout(
            Div(
                Div(Field('section', type='hidden'), css_class='col-md-8'),
                Div(Field('question', style='height:100px;'), css_class='col-md-8'),
                Div('weight', css_class='col-md-4'),
                css_class='row',
            ),
            Div(*choice_fields, css_class='row'),
            Div(
                Div(StrictButton('Update', css_class='btn-primary', css_id='question_update_btn'), css_class='col'),
                css_class='row'
            )
        )

questions/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404
from django.urls import reverse
from django.views import generic

from sections.models import Section

from .forms import QuestionForm
from .models import Question


class QuestionCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = QuestionForm
    model = Question
    template_name = 'questions/create.html'

    def get_initial(self):
        initial = super().get_initial()
        initial['section'] = get_object_or_404(Section, id=self.kwargs['section_pk'])
        return initial

    def get_success_url(self):
        return reverse('questions:create', kwargs={
            'qre_pk': self.kwargs['qre_pk'],
            'section_pk': self.kwargs['section_pk']
        })


class QuestionListView(LoginRequiredMixin, generic.ListView):
    model = Question
    template_name = 'questions/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.filter(section__pk=self.kwargs['section_pk'])

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['qre_pk'] = self.kwargs['qre_pk']
        context['section_pk'] = self.kwargs['section_pk']
        return context


class QuestionDetailView(LoginRequiredMixin, generic.DetailView):
    model = Question
    template_name = 'questions/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['qre_pk'] = self.kwargs['qre_pk']
        context['section_pk'] = self.kwargs['section_pk']
        return context


class QuestionMoveView(LoginRequiredMixin, generic.UpdateView):
    """Move section up/down in the qre by updating the order field using the Ordered Model 'up'/'down' methods."""

    model = Question
    fields = []

    def form_valid(self, form):

        direction = self.kwargs.get('direction')  # Accepts str 'up' or 'down'
        self.object = form.save()
        getattr(self.object, direction)()

        return HttpResponseRedirect(self.get_success_url())

    def get_success_url(self):
        return reverse('questions:list', kwargs={
            'qre_pk': self.kwargs['qre_pk'],
            'section_pk': self.kwargs['section_pk']
        })


class QuestionUpdateView(LoginRequiredMixin, generic.UpdateView):

    form_class = QuestionForm
    model = Question
    template_name = 'questions/update.html'

    def get_success_url(self):
        kwargs = {
            'qre_pk': self.kwargs['qre_pk'],
            'section_pk': self.kwargs['section_pk'],
            'pk': self.get_object().pk
        }
        return reverse('questions:update', kwargs=kwargs)


class QuestionDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Question
    template_name = 'questions/delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['qre_pk'] = self.kwargs['qre_pk']
        context['section_pk'] = self.kwargs['section_pk']
        return context

    def get_success_url(self):
        return reverse('sections:detail', kwargs={
            'qre_pk': self.kwargs['qre_pk'],
            'pk': self.kwargs['section_pk'],
        })

questions/templates/questions/create.html
{% load crispy_forms_tags %}

<form action="/" id="question_create_form" autocomplete="off">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" id="question_create_btn">Add question</button>
</form>

questions/templates/questions/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Delete Question{% endblock title %}

{% block breadcrumbs %}
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'dashboard:index' %}">dashboard</a></li>
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'qres:detail' qre_pk %}">{{ question.section.qre.name }}</a></li>
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'sections:detail' qre_pk section_pk %}">{{ question.section }}</a></li>
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'questions:detail' qre_pk section_pk question.pk %}">{{ question|truncatechars:40 }}</a></li>
  <li class="breadcrumb-item active" aria-current="page">delete question</li>
{% endblock breadcrumbs %}

{% block header %}
  Delete: {{ question }}
{% endblock header %}


{% block content %}
  <div class="row">
    <div class="col">
        <h5>This question and all its assessments will be permanently deleted. Are you sure you want to continue?</h5>
    </div>
  </div>
  <div class="row mt-4">
    <div class="col-md-6">
      <a href="{% url 'questions:detail' qre_pk section_pk question.pk %}" class="btn btn-primary">No, go back</a>
    </div>
    <div class="col-md-6 text-right">
      <form id="question_delete_form" method="POST">{% csrf_token %}
        <input class="btn btn-danger" type="submit" id="question_delete_btn" value="Yes, delete" />
      </form>
    </div>
  </div>

{% endblock content %}

questions/templates/questions/detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Question{% endblock title %}

{% block breadcrumbs %}
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'dashboard:index' %}">dashboard</a></li>
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'qres:detail' qre_pk %}">{{ question.section.qre }}</a></li>
<li class="breadcrumb-item" aria-current="page"><a href="{% url 'sections:detail' qre_pk section_pk %}">{{ question.section }}</a></li>
<li class="breadcrumb-item active" aria-current="page">Question</li>
{% endblock breadcrumbs %}

{% block header %}{{ question }}{% endblock header %}

{% block subheader %}
  <div class="row">
    <div class="col-md-12">
      <h4><span class="badge badge-primary">Weight <span id="question_weight">{{ question.weight }}</span></span></h4>
      <div>
        <span id="question_update_display"><a href="#"><i class="fas fa-pen"></i> Update</a></small></span> |
        <a href="{% url 'questions:delete' question.section.qre.pk question.section.pk question.pk %}" id="sections_delete_link"><i class="fas fa-trash-alt"></i> Delete</a>
      </div>
      <div id="question_update_div"></div>
    </div>
  </div>
{% endblock subheader %}

{% block content %}
  <div class="row">
    <div class="col">
      <h3>Choices</h3>
      <div class="card-deck">
        <div class="card">
          <div class="card-header">Choice 1</div>
          <div class="card-body" id="choice_text_1">{{ question.choice_text_1 }}</div>
        </div>
        <div class="card">
          <div class="card-header">Choice 2</div>
          <div class="card-body" id="choice_text_2">{{ question.choice_text_2 }}</div>
        </div>
        <div class="card">
          <div class="card-header">Choice 3</div>
          <div class="card-body" id="choice_text_3">{{ question.choice_text_3 }}</div>
        </div>
        <div class="card">
          <div class="card-header">Choice 4</div>
          <div class="card-body" id="choice_text_4">{{ question.choice_text_4 }}</div>
        </div>
        <div class="card">
          <div class="card-header">Choice 5</div>
          <div class="card-body" id="choice_text_5">{{ question.choice_text_5 }}</div>
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block page_data %}
  <div id="page_urls" data-question-update-url="{% url 'questions:update' qre_pk section_pk question.pk %}"></div>
{% endblock page_data %}

{% block admin_link %}
  <a target="_blank" href="{% url 'admin:questions_question_changelist' %}">Question admin</a>
{% endblock admin_link %}


{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/update_component.js' %}"></script>
  <script src="{% static 'questions/js/question-update.js' %}"></script>
{% endblock scripts %}

questions/templates/questions/list.html
{% for question in question_list %}
  <tr>
    <td width="5%" class="text-center">
      {% if not forloop.first %}
      <a href="#" class="question_move_link" data-url="{% url 'questions:move' qre_pk section_pk question.pk 'up' %}">
          <i class="fas fa-arrow-alt-circle-up"></i>
      </a>
      {% endif %}
    </td>
    <td width="5%" class="text-center">
      {% if not forloop.last %}
      <a href="#" class="question_move_link" data-url="{% url 'questions:move' qre_pk section_pk question.pk 'down' %}">
          <i class="fas fa-arrow-alt-circle-down"></i>
      </a>
      {% endif %}
    </td>
    <td><a href="{% url 'questions:detail' qre_pk section_pk question.pk %}">{{ question }}</a></td>
    <td width="10%" class="text-right">{{ question.weight }}</td>
  </tr>
{% endfor %}

questions/templates/questions/update.html
{% load crispy_forms_tags %}

{% crispy form %}
<div id="question_update_form_data" data-question="{{ question }}" data-weight="{{ question.weight }}" data-choice-text1="{{ question.choice_text_1 }}" data-choice-text2="{{ question.choice_text_2 }}"  data-choice-text3="{{ question.choice_text_3 }}" data-choice-text4="{{ question.choice_text_4 }}" data-choice-text5="{{ question.choice_text_5 }}"></div>