core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path, reverse

urlpatterns = [
    path('', lambda x: HttpResponseRedirect(reverse('dashboard:index'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('answers/', include('answers.urls')),
    path('clients/', include('clients.urls')),
    path('assessments/client-<int:client_pk>/', include('assessments.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('questionnaires/', include('questionnaires.urls')),
    path('sections/qre-<int:qre_pk>/', include('sections.urls')),
    path('questions/qre-<int:qre_pk>/section-<int:section_pk>/',
         include('questions.urls'))
]

questionnaires/urls.py
from django.urls import path

from . import views

app_name = 'qres'
urlpatterns = [
    path('create/', views.QreCreateView.as_view(), name='create'),
    path('list/', views.QreListView.as_view(), name='list'),
    path('detail-questionnaire-<int:pk>/', views.QreDetailView.as_view(), name='detail'),
    path('rename-questionnaire-<int:pk>/', views.QreRenameView.as_view(), name='rename'),
    path('delete-questionnaire-<int:pk>/', views.QreDeleteView.as_view(), name='delete'),
]

sections/urls.py
from django.urls import path, include

from . import views

app_name = 'sections'

urlpatterns = [

    path('create-section/',
         views.SectionCreateView.as_view(),
         name='create'),
    path('section-list/',
         views.SectionListView.as_view(),
         name='list'),
    path('move-section-<int:pk>-<direction>/',
         views.SectionMoveView.as_view(),
         name='move'),
    path('detail-section-<int:pk>/',
         views.SectionDetailView.as_view(),
         name='detail'),
    path('update-section-<int:pk>/',
         views.SectionUpdateView.as_view(),
         name='update'),
    path('delete-section-<int:pk>/',
         views.SectionDeleteView.as_view(),
         name='delete'),
]

questionnaires/models.py
from django.db import models

from questions.models import Question


# Create your models here.
class Qre(models.Model):
    name = models.CharField(max_length=55)
    org = models.ForeignKey(
        'orgs.Org', blank=True, null=True, related_name='qres',
        on_delete=models.SET_NULL, verbose_name='organisation'
    )

    class Meta:
        ordering = ('name',)
        verbose_name = 'questionnaire'

    def __str__(self):
        return self.name

    def get_questions(self):
        return Question.objects.filter(section__qre=self)

questionnaires/forms.py
from django import forms

from .models import Qre


class QreForm(forms.ModelForm):

    class Meta:
        model = Qre
        fields = ['name']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter name'}),
            'org': forms.HiddenInput(),
        }

questionnaires/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import QreForm
from .models import Qre


class QreCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = QreForm
    model = Qre
    template_name = 'qres/create.html'
    success_url = reverse_lazy('qres:create')

    def get_initial(self):
        initial = super().get_initial()
        initial['org'] = self.request.user.org
        return initial


class QreListView(LoginRequiredMixin, generic.ListView):
    model = Qre
    template_name = 'qres/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_superuser:
            return qs
        else:
            qs.filter(org=self.request.user.org)


class QreDetailView(LoginRequiredMixin, generic.DetailView):
    model = Qre
    template_name = 'qres/detail.html'


class QreRenameView(LoginRequiredMixin, generic.UpdateView):
    model = Qre
    template_name = 'qres/qre_rename.html'
    fields = ['name']

    def get_success_url(self):
        return reverse('qres:rename', kwargs={'pk': self.kwargs['pk']})


class QreDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Qre
    template_name = 'qres/delete.html'
    success_url = reverse_lazy('dashboard:index')

questionnaires/templates/qres/create.html
{% load crispy_forms_tags %}

<form action="/" id="qre_create_form" autocomplete="off">
    {% csrf_token %}
      {{ form|crispy }}
    <button class="btn btn-primary" id="qre_create_btn">Create</button>
</form>

questionnaires/templates/qres/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Delete Questionnaire
{% endblock title %}

{% block breadcrumbs %}
  <a href="{% url 'dashboard:index' %}">dashboard</a> / <a href="{% url 'qres:detail' object.pk %}">questionnaire</a> / delete
{% endblock breadcrumbs %}

{% block header %}
  Delete questionnaire "{{ object.name }}"
{% endblock header %}


{% block content %}
    <p>This questionnaire and all its questions and assessments will be deleted. Are you sure you want to continue?</p>
    <p><a href="{% url 'qres:detail' object.pk %}">No, go back</a></p>
    <br />

    <form id="qre_delete_form" method="POST">{% csrf_token %}
      <input type="submit" id="qre_delete_btn" value="Yes, delete" />
    </form>
{% endblock content %}

questionnaires/templates/qres/detail.html
{% extends 'base.html' %}
{% load static %}

{% block breadcrumbs %}
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'dashboard:index' %}">dashboard</a></li>
  <li class="breadcrumb-item active" aria-current="page">questionnaire</li>
{% endblock breadcrumbs %}

{% block title %}Questionnaire{% endblock title %}

{% block header %}{{ object.name }}{% endblock header %}

{% block subheader %}
  <div class="row">
    <div class="col-md-4">
        <div>
          <span id="qre_rename_display"><a href="#"><i class="fas fa-pen"></i> Rename</a></small></span> |
          <a href="{% url 'qres:delete' qre.pk %}" id="qre_delete_link"><i class="fas fa-trash-alt"></i> Delete</a>
        </div>
        <div id="qre_rename_div"></div>
    </div>
  </div>
{% endblock subheader %}

{% block content %}

  <!-- Section Create -->
  <div class="row">
    <div class="col">
      <h3>Sections</h3>
      <div id="section_div">
        <a href="#" id="section_create_display"><i class="fas fa-plus-circle"></i> Add section</a>
        <div id="section_create_div"></div>
      </div>
    </div>
  </div>
  <!-- End Section Create -->

  <!-- Section Table -->
  <div class="row">
    <div class="col">
      <table class="table mt-4" id="assess_table">
        <thead>
          <tr>
            <th width="5%">Move up</th>
            <th width="5%">Move down</th>
            <th>Section</th>
          </tr>
        </thead>
        <tbody id="section_table_body">
        {% with object_list=qre.sections.all qre_pk=qre.pk %}
          {% include 'sections/list.html' %}
        {% endwith %}
        </tbody>
        <tfoot>
          <tr>
            <th></th>
            <th></th>
            <th></th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <!-- End Section Table -->

  <!-- Section Move Form -->
  <form id="section_move_form">
    {% csrf_token %}
  </form>
  <!-- End Section Move Form-->
{% endblock content %}

{% block page_data %}
  <div id="page_urls" data-qre-rename-url="{% url 'qres:rename' object.pk %}" data-section-create-url="{% url 'sections:create' object.pk %}" data-section-list-url="{% url 'sections:list' object.pk %}"></div>
{% endblock page_data %}

{% block admin_link %}
  <a target="_blank" href="{% url 'admin:questionnaires_qre_changelist' %}">Questionnaire admin</a>
{% endblock admin_link %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/create_component.js' %}"></script>
  <script src="{% static 'qres/js/qre-create-section.js' %}"></script>
  <script src="{% static 'js/update_component.js' %}"></script>
  <script src="{% static 'qres/js/qre-rename.js' %}"></script>
  <script src="{% static 'sections/js/move.js' %}"></script>
{% endblock scripts %}

questionnaires/templates/qres/list.html
<ul class="list-group scroll">
  {% for qre in qre_list %}
  <li class="list-group-item border-primary"><a href="{% url 'qres:detail' qre.pk %}">{{ qre }}</a></li>
  {% endfor %}
</ul>

questionnaires/templates/qres/qre_rename.html
{% load crispy_forms_tags %}

<form action="/" id="qre_rename_form">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" id="qre_rename_btn">Update</button>
</form>
<div id="qre_rename_form_data" data-qre-name="{{ object.name }}"></div>

questionnaires/templates/qres/question_list.html
{% for question in question_list %}
  <p>{{ question }}</p>
{% endfor %}

questionnaires/templates/qres/section_create.html
<form action="/" id="qre_section_create_form" autocomplete="off">
    {% csrf_token %}
    {{ form }}
    <button id="qre_section_create_btn">Create section</button>
</form>

questionnaires/templates/qres/section_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Delete Section
{% endblock title %}

{% block breadcrumbs %}
  <a href="{% url 'dashboard:index' %}">dashboard</a> /
  <a href="{% url 'qres:detail' view.kwargs.qre_id %}">questionnaire: "{{ object.qre.name }}"</a> /
  <a href="{% url 'qres:section_detail' view.kwargs.qre_id object.id %}">section: "{{ object.name }}"</a> /
  delete
{% endblock breadcrumbs %}

{% block header %}
  Delete section "{{ object.name }}"
{% endblock header %}


{% block content %}
    <p>This section and all its questions and assessments will be deleted. Are you sure you want to continue?</p>
    <p><a href="{% url 'qres:section_detail' object.pk object.id %}">No, go back</a></p>
    <br />

    <form id="qre_section_delete_form" method="POST">{% csrf_token %}
      <input type="submit" id="qre_section_delete_btn" value="Yes, delete" />
    </form>
{% endblock content %}

questionnaires/templates/qres/section_detail.html
{% extends 'base.html' %}
{% load static %}
{% block title %}
  Questionnaire
{% endblock title %}
{% block breadcrumbs %}
  <a href="{% url 'dashboard:index' %}">dashboard</a> /
  <a href="{% url 'qres:detail' view.kwargs.qre_id %}">questionnaire: "{{ object.qre.name }}"</a> /
  section
{% endblock breadcrumbs %}
{% block header %}
  {{ object.name }}
{% endblock header %}
{% block content %}
<p><a href="#" id="update_qre_section_link">~ Edit section</a></p>
<div id="qre_section_update_div" hidden></div>
<hr>
<!-- Questions -->
  <div id="qre_qns_div">
    <h3>Questions</h3>
  </div>
  <br>
  <br>
  <div id="qre_question_list_div">
    {% include 'qres/question_list.html' %}
  </div>
<!-- End Questions -->
<hr>
<p><a href="{% url 'qres:section_delete' view.kwargs.qre_id object.pk %}">- Delete section</a></p>
<p><a target="_blank" href="/admin/">Go to admin site</a></p>
{% endblock content %}

{% block page_data %}
  <div id="page_urls" data-qre-section-update-url="{% url 'qres:section_update' object.qre.id object.pk %}"></div>
{% endblock page_data %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'qres/js/section_update.js' %}"></script>
{% endblock scripts %}

questionnaires/templates/qres/section_update.html
<form action="/" id="qre_section_update_form" autocomplete="off">
    {% csrf_token %}
    {{ form }}
    <button id="qre_section_update_btn">Update</button>
</form>
<div id="qre_section_update_form_data" data-qre-name="{{ object.name }}"></div>