assessments/urls.py
from django.urls import path

from . import views

app_name = 'assess'

urlpatterns = [
    path('create-assessment/', views.AssessmentCreateView.as_view(), name='create'),
    path('assessment-list/', views.AssessmentListView.as_view(), name='list'),
    path('detail-assessment-<int:pk>/', views.AssessmentDetailView.as_view(), name='detail'),
    path('rename-assessment-<int:pk>/', views.AssessmentRenameView.as_view(), name='rename'),
    # path('update-assessment-<int:pk>/', views.AssessmentUpdateView.as_view(), name='update'),
    path('complete-assessment-<int:pk>/', views.AssessmentCompleteView.as_view(), name='complete'),
    path('delete-assessment-<int:pk>/', views.AssessmentDeleteView.as_view(), name='delete'),
]

clients/urls.py
from django.urls import path

from . import views

app_name = 'clients'
urlpatterns = [
    path('create/', views.ClientCreateView.as_view(), name='create'),
    path('list/', views.ClientListView.as_view(), name='list'),
    path('detail-client-<int:pk>/', views.ClientDetailView.as_view(), name='detail'),
    path('update-client-<int:pk>/', views.ClientUpdateView.as_view(), name='update'),
    path('delete-client-<int:pk>/', views.ClientDeleteView.as_view(), name='delete'),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path, reverse

urlpatterns = [
    path('', lambda x: HttpResponseRedirect(reverse('dashboard:index'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('answers/', include('answers.urls')),
    path('clients/', include('clients.urls')),
    path('assessments/client-<int:client_pk>/', include('assessments.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('questionnaires/', include('questionnaires.urls')),
    path('sections/qre-<int:qre_pk>/', include('sections.urls')),
    path('questions/qre-<int:qre_pk>/section-<int:section_pk>/',
         include('questions.urls'))
]

clients/models.py
from django.db import models


class Client(models.Model):
    name = models.CharField(max_length=55, unique=True)
    org = models.ForeignKey(
        'orgs.Org',
        related_name='clients',
        blank=True,
        null=True,
        on_delete=models.SET_NULL
    )

    class Meta:
        ordering = ('name',)

    def __str__(self):
        return self.name

clients/forms.py
from django import forms

from .models import Client


class ClientForm(forms.ModelForm):
    """A representation of a third party who is the subject of questionnaire assessments."""

    class Meta:
        model = Client
        fields = ['name', 'org']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'Enter name'}),
            'org': forms.HiddenInput(),
        }

clients/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.views import generic

from .forms import ClientForm
from .models import Client


class ClientCreateView(LoginRequiredMixin, generic.CreateView):
    form_class = ClientForm
    model = Client
    template_name = 'clients/create.html'
    success_url = reverse_lazy('clients:create')

    def get_initial(self):
        initial = super().get_initial()
        initial['org'] = self.request.user.org
        return initial


class ClientListView(generic.ListView):
    model = Client
    template_name = 'clients/list.html'

    def get_queryset(self):
        qs = super().get_queryset()
        if self.request.user.is_superuser:
            return qs
        else:
            qs.filter(org=self.request.user.org, id=self.request.user.client.id)


class ClientDetailView(LoginRequiredMixin, generic.DetailView):
    model = Client
    template_name = 'clients/detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['assessment_list'] = self.object.assessments.all()
        return context


class ClientUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Client
    template_name = 'clients/update.html'
    fields = ['name']

    def get_success_url(self):
        return reverse('clients:update', kwargs={'pk': self.kwargs['pk']})


class ClientDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Client
    template_name = 'clients/delete.html'
    success_url = reverse_lazy('dashboard:index')

clients/templates/clients/create.html
{% load crispy_forms_tags %}

<form action="/" id="client_create_form" autocomplete="off">
    {% csrf_token %}
    {{ form|crispy }}
    <button type="button" class="btn btn-primary" id="client_create_btn">Create</button>
</form>

clients/templates/clients/delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
  Delete Client
{% endblock title %}

{% block breadcrumbs %}
  <a href="{% url 'dashboard:index' %}">dashboard</a> / <a href="{% url 'clients:detail' client.pk %}">client</a> / delete
{% endblock breadcrumbs %}

{% block header %}
  Delete client "{{ client.name }}"
{% endblock header %}


{% block content %}
    <p>This client and all its assessments will be deleted. Are you sure you want to continue?</p>
    <p><a href="{% url 'clients:detail' client.pk %}">No, go back</a></p>
    <br />

    <form id="client_delete_form" method="POST">{% csrf_token %}
      <input type="submit" id="client_delete_btn" value="Yes, delete" />
    </form>
{% endblock content %}

clients/templates/clients/detail.html
{% extends 'base.html' %}
{% load static %}

{% block styles %}
  {{ block.super }}
  <link rel="stylesheet" type="text/css" href="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.css"/>
{% endblock %}

{% block breadcrumbs %}
  <li class="breadcrumb-item" aria-current="page"><a href="{% url 'dashboard:index' %}">dashboard</a></li>
  <li class="breadcrumb-item active" aria-current="page">client</li>
{% endblock breadcrumbs %}

{% block title %}Client{% endblock title %}

{% block header %}{{ client }}{% endblock header %}
{% block subheader %}
  <div class="row">
    <div class="col-md-4">
        <p><span id="client_update_display"><a href="#"><i class="fas fa-pen"></i> Rename client</a></small></span> | <a href="{% url 'clients:delete' client.pk %}" id="client_delete_link"><i class="fas fa-trash-alt"></i> Delete client</a></p>
        <div id="client_update_div"></div>
    </div>
  </div>
{% endblock subheader %}

{% block content %}
  <!-- Assessments -->
  <div id="assess_div">
    <h3>Assessments</h3>
    <a href="#" id="assess_create_display"><i class="fas fa-plus-circle"></i> New assessment</a>
    <div id="assess_create_div"></div>
    <div>
      <table class="table table-striped" id="assess_table">
        <thead class="bg-primary text-white">
          <tr>
            <th>Name</th>
            <th>Date</th>
            <th>Questionnaire</th>
            <th>Score</th>
            <th>Max Score</th>
            <th>Maturity</th>
          </tr>
        </thead>
        <tbody class="border-primary" id="assess_table_body">
            {% include 'assess/list.html' %}
        </tbody>
        <tfoot>
          <tr>
            <th></th>
            <th></th>
            <th></th>
            <th></th>
            <th class="text-right pr-4"></th>
            <th class="text-right pr-4"></th>
          </tr>
        </tfoot>
      </table>
    </div>
  </div>
  <!-- End Assessments -->

  {% endblock content %}
  {% block page_data %}
  <div id="page_urls" data-client-update-url="{% url 'clients:update' client.pk %}" data-assess-create-url="{% url 'assess:create' client.pk %}" data-assess-list-url="{% url 'assess:list' client.pk %}"></div>
  {% endblock page_data %}

  {% block admin_link %}
    <a target="_blank" href="{% url 'admin:clients_client_changelist' %}">client admin</a>
  {% endblock admin_link %}

{% block scripts %}
  {{ block.super }}
  <script type="text/javascript" src="https://cdn.datatables.net/v/bs4/dt-1.10.18/r-2.2.2/datatables.min.js"></script>
  <script src="{% static 'assess/js/table.js' %}"></script>
  <script src="{% static 'js/create_component.js' %}"></script>
  <script src="{% static 'js/update_component.js' %}"></script>
  <script src="{% static 'clients/js/update_client.js' %}"></script>
  <script src="{% static 'clients/js/create_assessment.js' %}"></script>
{% endblock scripts %}

clients/templates/clients/list.html
<ul class="list-group scroll">
  {% for client in client_list %}
  <li class="list-group-item border-primary"><a href="{% url 'clients:detail' client.pk %}">{{ client }}</a></li>
  {% endfor %}
</ul>

clients/templates/clients/update.html
{% load crispy_forms_tags %}

<form action="/" id="client_update_form">
    {% csrf_token %}
    {{ form|crispy }}
    <button class="btn btn-primary" id="client_update_btn">Update</button>
</form>
<div id="client_update_form_data" data-client-name="{{ client }}"></div>