assessments/urls.py
from django.urls import path

from . import views

app_name = 'assess'

urlpatterns = [
    path('create-assessment/', views.AssessmentCreateView.as_view(), name='create'),
    path('assessment-list/', views.AssessmentListView.as_view(), name='list'),
    path('detail-assessment-<int:pk>/', views.AssessmentDetailView.as_view(), name='detail'),
    path('rename-assessment-<int:pk>/', views.AssessmentRenameView.as_view(), name='rename'),
    # path('update-assessment-<int:pk>/', views.AssessmentUpdateView.as_view(), name='update'),
    path('complete-assessment-<int:pk>/', views.AssessmentCompleteView.as_view(), name='complete'),
    path('delete-assessment-<int:pk>/', views.AssessmentDeleteView.as_view(), name='delete'),
]

clients/urls.py
from django.urls import path

from . import views

app_name = 'clients'
urlpatterns = [
    path('create/', views.ClientCreateView.as_view(), name='create'),
    path('list/', views.ClientListView.as_view(), name='list'),
    path('detail-client-<int:pk>/', views.ClientDetailView.as_view(), name='detail'),
    path('update-client-<int:pk>/', views.ClientUpdateView.as_view(), name='update'),
    path('delete-client-<int:pk>/', views.ClientDeleteView.as_view(), name='delete'),
]

core/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.http import HttpResponseRedirect
from django.urls import include, path, reverse

urlpatterns = [
    path('', lambda x: HttpResponseRedirect(reverse('dashboard:index'))),
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('answers/', include('answers.urls')),
    path('clients/', include('clients.urls')),
    path('assessments/client-<int:client_pk>/', include('assessments.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('questionnaires/', include('questionnaires.urls')),
    path('sections/qre-<int:qre_pk>/', include('sections.urls')),
    path('questions/qre-<int:qre_pk>/section-<int:section_pk>/',
         include('questions.urls'))
]

dashboard/urls.py
from django.urls import path

from .views import DashboardIndexView


app_name = 'dashboard'
urlpatterns = [
    path('', DashboardIndexView.as_view(), name='index'),
]

questionnaires/urls.py
from django.urls import path

from . import views

app_name = 'qres'
urlpatterns = [
    path('create/', views.QreCreateView.as_view(), name='create'),
    path('list/', views.QreListView.as_view(), name='list'),
    path('detail-questionnaire-<int:pk>/', views.QreDetailView.as_view(), name='detail'),
    path('rename-questionnaire-<int:pk>/', views.QreRenameView.as_view(), name='rename'),
    path('delete-questionnaire-<int:pk>/', views.QreDeleteView.as_view(), name='delete'),
]

dashboard/models.py
from django.db import models

# Create your models here.

dashboard/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.models import Site
from django.views.generic import TemplateView

from .utils import get_assess_list, get_client_list, get_qre_list


class DashboardIndexView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context['client_list'] = get_client_list()
        context['qre_list'] = get_qre_list()
        context['recent_assess_list'] = get_assess_list()[:10]
        context['site'] = Site.objects.get_current()

        return context

dashboard/templates/dashboard/dashboard.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block breadcrumbs %}
<li class="breadcrumb-item active" aria-current="page">dashboard</li>
{% endblock breadcrumbs %}

{% block header %}{% endblock header %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <div class="card-deck">
        <div class="card border-primary">
          <div class="card-header text-white bg-primary mb-3 "><strong>Clients</strong></div>
          <div class="card-body border-primary">
            <div id="client_list_div">
                {% include 'clients/list.html' %}
            </div>
          </div>
        </div>
        <div class="card border-primary">
          <div class="card-header text-white bg-primary mb-3"><strong>Questionnaires</strong></div>
          <div class="card-body">
            <div id="qre_list_div">
              {% include 'qres/list.html' %}
            </div>
          </div>
        </div>
        <div class="card border-primary">
          <div class="card-header text-white bg-primary mb-3"><strong>Recent assessments</strong></div>
          <div class="card-body">
            <ul class="list-group scroll">
              {% for assess in recent_assess_list %}
              <li class="list-group-item border-primary">
                <a href="{% url 'assess:detail' assess.client.pk assess.pk %}">
                  {{ assess }}<small>&nbsp;&nbsp;&#8209;&nbsp;{{assess.client }}</small>
                </a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row pt-1">
    <div class="col-12">
      <div class="card-deck">
        <div class="card border-0">
          <div class="card-body">
              <h5 class="text-center"><a href="#" id="client_create_display"><i class="fas fa-plus-circle"></i></a></h5>
            <div id="client_create_div"></div>
          </div>
        </div>
        <div class="card border-0">
          <div class="card-body">
            <h5 class="text-center"><a href="#" id="qre_create_display"><i class="fas fa-plus-circle"></i></a></h5>
            <div id="qre_create_div"></div>
          </div>
        </div>
        <div class="card border-0">
        </div>
      </div>
    </div>
  </div>
{% endblock content %}

{% block page_data %}
  <div id="page_urls" data-qre-create-url="{% url 'qres:create' %}" data-qre-list-url="{% url 'qres:list' %}" data-client-create-url="{% url 'clients:create' %}" data-client-list-url="{% url 'clients:list' %}"></div>
{% endblock page_data %}

{% block admin_link %}
  <a target="_blank" href="{% url 'admin:index' %}">Site admin</a>
{% endblock admin_link %}

{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/create_component.js' %}"></script>
  <script src="{% static 'dashboard/js/create_objects.js' %}"></script>
{% endblock scripts %}

dashboard/templates/dashboard/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Dashboard{% endblock title %}

{% block styles %}
{{ block.super }}
<link href="https://fonts.googleapis.com/css?family=Muli|Orbitron:900" rel="stylesheet">
{% endblock styles %}

{% block header %}<span class="brand">{{ site.name }}</span>{% endblock header %}

{% block breadcrumbs %}
  <li class="breadcrumb-item active" aria-current="page">dashboard</li>
{% endblock breadcrumbs %}

{% block content %}
  <div class="row">
    <div class="col-12">
      <div class="card-deck">
        <div class="card">
          <div class="card-header">Clients</div>
          <div class="card-body">
            <div id="client_list_div">
                {% include 'clients/list.html' %}
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">Questionnaires</div>
          <div class="card-body">
            <div id="qre_list_div">
              {% include 'qres/list.html' %}
            </div>
          </div>
        </div>
        <div class="card">
          <div class="card-header">Recent assessments</div>
          <div class="card-body">
            <ul class="list-group scroll">
              {% for assess in recent_assess_list %}
              <li class="list-group-item">
                <a href="{% url 'assess:detail' assess.client.pk assess.pk %}">
                  {{ assess }}<small>&nbsp;&nbsp;&#8209;&nbsp;{{assess.client }}</small>
                </a></li>
              {% endfor %}
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row pt-1">
    <div class="col-12">
      <div class="card-deck">
        <div class="card">
          <div class="card-body">
              <h5 class="text-center"><a href="#" id="client_create_display"><i class="fas fa-plus-circle"></i></a></h5>
            <div id="client_create_div"></div>
          </div>
        </div>
        <div class="card">
          <div class="card-body">
            <h5 class="text-center"><a href="#" id="qre_create_display"><i class="fas fa-plus-circle"></i></a></h5>
            <div id="qre_create_div"></div>
          </div>
        </div>
        <div class="card">
        </div>
      </div>
    </div>
  </div>
  <br>
  <hr>
  <p class="text-right"><a target="_blank" href="{% url 'admin:index' %}"><i class="fas fa-tachometer-alt"></i> Go to site admin</a></p>

{% endblock content %}
{% block page_data %}
  <div id="page_urls" data-qre-create-url="{% url 'qres:create' %}" data-qre-list-url="{% url 'qres:list' %}" data-client-create-url="{% url 'clients:create' %}" data-client-list-url="{% url 'clients:list' %}"></div>
{% endblock page_data %}
{% block scripts %}
  {{ block.super }}
  <script src="{% static 'js/create_component.js' %}"></script>
  <script src="{% static 'dashboard/js/create_objects.js' %}"></script>
{% endblock scripts %}